# https://github.com/pages-themes/time-machine?tab=readme-ov-file
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

title: Sad Zero's Blog
description: The flower snow is flying